AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation for RDS with MySQL engine in VPC
Parameters:
  VpcId:
    Type: String
    Description: VpcId of your existing Virtual Private Cloud (VPC)
  Subnets:
    Type: CommaDelimitedList
    Description: The list of SubnetIds, one in each Availability Zone in the region
      in your Virtual Private Cloud (VPC)
  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
  DBUsername:
    Default: admin
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
  DBPassword:
    Default: password
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: "[a-zA-Z0-9]*"
  DBClass:
    Default: db.t2.micro
    Description: Database instance class
    Type: String
    AllowedValues:
    - db.t2.micro
    - db.t3.micro
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'

Resources:
  SwaDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds:
        Ref: Subnets
  
  SwaDBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: Security group for RDS DB Instance
      EC2VpcId:
        Ref: VpcId
  
  SwaTestDataDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AvailabilityZone: us-east-1b
      DBName:
        Ref: DBName
      AllocatedStorage:
        Ref: DBAllocatedStorage
      DBInstanceClass:
        Ref: DBClass
      Engine: MySQL
      EngineVersion: '5.5'
      MasterUsername:
        Ref: DBUsername
      MasterUserPassword:
        Ref: DBPassword
      DBSubnetGroupName:
        Ref: SwaDBSubnetGroup
      DBSecurityGroups:
      - Ref: SwaDBSecurityGroup
Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value:
      Fn::Join:
      - ''
      - - jdbc:mysql://
        - Fn::GetAtt:
          - SwaTestDataDB
          - Endpoint.Address
        - ":"
        - Fn::GetAtt:
          - SwaTestDataDB
          - Endpoint.Port
        - "/"
        - Ref: DBName
